### ISSUE TITLE
$firebase has been removed

### ISSUE THREAD

**Issue by francisrod01** [mappmechanic/ionic-firebase#5]
You may instantiate $firebaseArray and $firebaseObject directly now.

``` bash
Error: $firebase has been removed. You may instantiate $firebaseArray and $firebaseObject directly now. For simple write operations, just use the Firebase ref directly. See the AngularFire 1.0.0 changelog for details: https://www.firebase.com/docs/web/libraries/angular/changelog.html
    at http://192.168.33.20:8100/externals/angular-fire/angularfire.min.js:12:14225
    at Object.<anonymous> (http://192.168.33.20:8100/js/services.js:11:21)
    at Object.invoke (http://192.168.33.20:8100/lib/ionic/js/ionic.bundle.js:13277:17)
    at Object.enforcedReturnValue [as $get] (http://192.168.33.20:8100/lib/ionic/js/ionic.bundle.js:13130:37)
    at Object.invoke (http://192.168.33.20:8100/lib/ionic/js/ionic.bundle.js:13277:17)
    at http://192.168.33.20:8100/lib/ionic/js/ionic.bundle.js:13095:37
    at getService (http://192.168.33.20:8100/lib/ionic/js/ionic.bundle.js:13236:39)
    at invoke (http://192.168.33.20:8100/lib/ionic/js/ionic.bundle.js:13268:13)
    at Object.instantiate (http://192.168.33.20:8100/lib/ionic/js/ionic.bundle.js:13285:27)
    at http://192.168.33.20:8100/lib/ionic/js/ionic.bundle.js:17841:28 <ion-nav-view name="tab-rooms" class="view-container tab-content" nav-view="active" nav-view-transition="ios">(anonymous function) @ ionic.bundle.js:21157$get @ ionic.bundle.js:17936invokeLinkFn @ ionic.bundle.js:17479nodeLinkFn @ ionic.bundle.js:16977compositeLinkFn @ ionic.bundle.js:16368publicLinkFn @ ionic.bundle.js:16243tabSelected @ ionic.bundle.js:58849$get.Scope.$digest @ ionic.bundle.js:24510$get.Scope.$apply @ ionic.bundle.js:24778done @ ionic.bundle.js:19191completeRequest @ ionic.bundle.js:19363requestLoaded @ ionic.bundle.js:19304
app.js:43 Logged in as : simplelogin:2
```

**Comment by batistafrancis** [comment]
[Solved]

``` javascript
factory('Rooms', function ($firebaseArray) {

    ...

    var rooms = $firebaseArray(ref.child('rooms'));
    ...
```
